name: SonarCloud Scan - Administration

on:
  push:
    branches:
      - main
    paths:
      - 'Administration/**'

  pull_request:
    paths:
      - 'Administration/**'

jobs:
  sonarcloud:
    name: SonarCloud Scan for Administration
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Administration

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze with SonarCloud
        run: mvn clean verify sonar:sonar \
          -Dsonar.projectKey=brew_and_bugs_Administration \
          -Dsonar.organization=brew-and-bugs \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
